import { Link } from 'react-router-dom';
import './legal.css';

const sections = [
  'Acceptance of Terms',
  'Description of Services',
  'Account Registration',
  'User Responsibilities',
  'Subscription Plans and Billing',
  'Free Trial',
  'Merchandise Purchases',
  'Personalized Content and Digital Services',
  'Community Guidelines',
  'Email Communications',
  'Intellectual Property',
  'Limitation of Liability',
  'Disclaimer of Warranties',
  'Termination',
  'Governing Law',
  'Changes to These Terms',
  'Contact Information',
];

export default function TermsOfUse() {
  return (
    <div className="legal-page">
      <h1 className="legal-heading">Terms of Use</h1>
      <p className="legal-last-updated">Last updated: March 26, 2026</p>

      <nav className="legal-toc">
        <h3>Table of Contents</h3>
        <ol>
          {sections.map((s, i) => (
            <li key={i}><a href={`#terms-${i + 1}`}>{s}</a></li>
          ))}
        </ol>
      </nav>

      <section className="legal-section" id="terms-1">
        <h2 className="legal-subheading">1. Acceptance of Terms</h2>
        <p>
          By accessing or using the Hyrax Fitness website, mobile application, or any
          services provided by Hyrax Fitness ("we," "us," or "our"), you agree to be
          bound by these Terms of Use. If you do not agree to these terms, please do
          not use our services.
        </p>
        <p>
          These terms apply to all visitors, registered users, and anyone who accesses
          or uses the Hyrax Fitness platform.
        </p>
      </section>

      <section className="legal-section" id="terms-2">
        <h2 className="legal-subheading">2. Description of Services</h2>
        <p>
          Hyrax Fitness provides a start-stop, scramble-and-carry training system
          inspired by the rock hyrax. Our services include, but are not limited to:
        </p>
        <ul>
          <li>Access to structured fitness training programs and workout plans</li>
          <li>Personalized workout routines and nutrition plans generated by automated systems based on your profile data</li>
          <li>A digital coaching feature for fitness, nutrition, and recovery guidance</li>
          <li>Meal logging and nutritional tracking tools</li>
          <li>Online training content including exercise descriptions, workout formats, videos, and coaching guidance</li>
          <li>Account management, progress tracking, and benchmark features</li>
          <li>A branded merchandise store where you can browse and purchase Hyrax Fitness gear and apparel</li>
          <li>Community forum and support ticket system</li>
          <li>Event information and resources</li>
        </ul>
        <p>
          We reserve the right to modify, suspend, or discontinue any part of our
          services at any time without prior notice.
        </p>
      </section>

      <section className="legal-section" id="terms-3">
        <h2 className="legal-subheading">3. Account Registration</h2>
        <p>
          To access certain features, you must create an account by providing accurate
          and complete information. You may register using your email address or through
          Google sign-in. You are responsible for maintaining the confidentiality of
          your account credentials and for all activities that occur under your account.
        </p>
        <p>
          You must notify us immediately of any unauthorized use of your account. We
          are not liable for any loss or damage arising from your failure to protect
          your login information.
        </p>
        <p>
          You must be at least 18 years of age to create an account and use our services.
        </p>
      </section>

      <section className="legal-section" id="terms-4">
        <h2 className="legal-subheading">4. User Responsibilities</h2>
        <p>
          By using our fitness training services, you acknowledge and agree to the following:
        </p>
        <ul>
          <li>
            <strong>Medical clearance:</strong> You should consult with a qualified
            healthcare provider before beginning any exercise program or nutrition plan,
            particularly if you have pre-existing health conditions, food allergies,
            injuries, or concerns about your physical fitness.
          </li>
          <li>
            <strong>Personal responsibility:</strong> You are solely responsible for
            your physical well-being during any training activities and for verifying
            that any nutrition plans are safe for your specific dietary needs and
            allergies. Exercise and dietary changes inherently carry risk, and you
            participate at your own risk.
          </li>
          <li>
            <strong>Proper form:</strong> It is your responsibility to use proper form
            and technique when performing exercises. We recommend working with a
            qualified trainer if you are unsure about exercise execution.
          </li>
          <li>
            <strong>Honest information:</strong> You agree to provide accurate health,
            fitness, allergy, and dietary information when requested, such as through
            fitness and nutrition questionnaires. Inaccurate information may result in
            unsuitable recommendations.
          </li>
          <li>
            <strong>Acceptable use:</strong> You agree not to misuse the platform,
            share your account credentials, reverse-engineer our systems, or use the
            platform for any unlawful purpose. You agree not to use automated tools,
            bots, or scripts to access the platform in a manner that exceeds
            reasonable use. Excessive or abusive requests may be throttled or blocked.
          </li>
        </ul>
      </section>

      <section className="legal-section" id="terms-5">
        <h2 className="legal-subheading">5. Subscription Plans and Billing</h2>
        <p>
          Hyrax Fitness offers three subscription tiers with varying levels of access:
        </p>
        <ul>
          <li><strong>Pup (Free):</strong> Access to signature workouts, training videos, community forum, and basic features.</li>
          <li><strong>Rock Runner ($5/month):</strong> Everything in Pup plus personalized daily workout routines.</li>
          <li><strong>Iron Dassie ($20/month):</strong> Everything in Rock Runner plus personalized nutrition plans and digital coaching.</li>
        </ul>
        <p>
          Paid subscriptions are billed monthly and auto-renew until cancelled. Payment
          is processed securely through Stripe. Hyrax Fitness does not store your full
          payment card details.
        </p>
        <ul>
          <li><strong>Upgrades</strong> take effect immediately, with prorated charges for the remainder of the current billing period.</li>
          <li><strong>Downgrades</strong> take effect at the end of the current billing period. You retain access to your current tier's features until then.</li>
          <li><strong>Cancellation</strong> can be initiated at any time through your portal. You will retain access to paid features until the end of your current billing period, after which your account reverts to the free Pup tier.</li>
        </ul>
        <p>
          We reserve the right to change subscription pricing. Existing subscribers
          will be notified of price changes in advance and will retain their current
          rate until their next renewal after the change takes effect.
        </p>
      </section>

      <section className="legal-section" id="terms-6">
        <h2 className="legal-subheading">6. Free Trial</h2>
        <p>
          New accounts receive a complimentary 7-day free trial with access to all
          Iron Dassie (premium) features, including personalized workout routines,
          nutrition plans, and digital coaching. No payment information is required
          to start the trial.
        </p>
        <p>
          At the end of the trial period, your account will automatically revert to
          the free Pup tier unless you choose to subscribe to a paid plan. The free
          trial is offered once per account and cannot be extended or restarted.
        </p>
      </section>

      <section className="legal-section" id="terms-7">
        <h2 className="legal-subheading">7. Merchandise Purchases</h2>
        <p>
          Hyrax Fitness offers branded merchandise through our Merch page. Merchandise
          orders are fulfilled by Fourthwall, a third-party commerce platform.
        </p>
        <ul>
          <li>
            Payment for merchandise is processed directly by Fourthwall during
            checkout. Hyrax Fitness does not handle or store your merch payment
            details.
          </li>
          <li>
            Merchandise orders are subject to Fourthwall's terms of service and
            applicable policies.
          </li>
          <li>
            Returns, exchanges, and refunds for merchandise are handled in accordance
            with Fourthwall's return policy.
          </li>
          <li>
            Hyrax Fitness sends order confirmation and shipping notification emails
            based on order data received from Fourthwall.
          </li>
          <li>
            Product availability, pricing, and shipping times are subject to change
            without prior notice.
          </li>
        </ul>
        <p>
          Merchandise purchases are separate from subscription billing. Your
          subscription tier and merch purchases are managed independently.
        </p>
      </section>

      <section className="legal-section" id="terms-8">
        <h2 className="legal-subheading">8. Personalized Content and Digital Services</h2>
        <p>
          Hyrax Fitness uses automated systems to generate personalized workout
          routines, nutrition plans, and coaching responses based on the information
          you provide through your profile, questionnaires, activity history, and
          meal logs.
        </p>
        <ul>
          <li>
            <strong>Not professional advice:</strong> All generated content is for
            informational and educational purposes only. It does not constitute
            medical, nutritional, therapeutic, or professional health advice. Always
            consult qualified healthcare providers before starting or modifying any
            fitness or nutrition program.
          </li>
          <li>
            <strong>Allergy and dietary safety:</strong> Nutrition plans take into
            account allergies and dietary restrictions you report in your profile.
            However, you are solely responsible for verifying that all recommended
            foods are safe for your specific needs. Hyrax Fitness is not liable for
            allergic reactions, adverse health effects, or any harm resulting from
            following generated nutrition plans.
          </li>
          <li>
            <strong>Digital coaching:</strong> The coaching feature provides guidance
            on fitness, nutrition, and recovery topics only. It is limited to 20
            messages per day and is not a substitute for working with a certified
            personal trainer, dietitian, or medical professional.
          </li>
          <li>
            <strong>Personal use only:</strong> Generated workout routines, nutrition
            plans, and coaching responses are provided for your personal use. You may
            not redistribute, resell, or commercially exploit this content.
          </li>
        </ul>
      </section>

      <section className="legal-section" id="terms-9">
        <h2 className="legal-subheading">9. Community Guidelines</h2>
        <p>
          Hyrax Fitness provides a community forum where users can share experiences,
          ask questions, and engage with other members. By posting content to the
          community forum, you agree to the following:
        </p>
        <ul>
          <li>You grant Hyrax Fitness a non-exclusive, royalty-free license to display your content on the platform for as long as the content remains posted.</li>
          <li>You retain ownership of your original content and may request its removal at any time.</li>
          <li>Anonymous posting is available. Hyrax Fitness staff may view authorship information for moderation purposes only.</li>
          <li>You must not post content that is harmful, threatening, abusive, misleading, defamatory, or offensive, or that violates the rights of others.</li>
          <li>Hyrax Fitness reserves the right to moderate, edit, or remove any content at its sole discretion, without prior notice.</li>
        </ul>
      </section>

      <section className="legal-section" id="terms-10">
        <h2 className="legal-subheading">10. Email Communications</h2>
        <p>
          By creating an account, you agree to receive the following types of email
          communications from Hyrax Fitness:
        </p>
        <ul>
          <li>
            <strong>Account emails (required):</strong> Verification codes, password
            resets, and security notifications. These cannot be opted out of as they
            are necessary for account functionality.
          </li>
          <li>
            <strong>Transactional emails:</strong> Subscription confirmations, payment
            notifications, support ticket replies, and trial reminders. You can manage
            these through the notification preferences in your portal Settings.
          </li>
        </ul>
        <p>
          Hyrax Fitness will not send marketing or promotional emails without your
          explicit consent.
        </p>
      </section>

      <section className="legal-section" id="terms-11">
        <h2 className="legal-subheading">11. Intellectual Property</h2>
        <p>
          All content on the Hyrax Fitness platform, including but not limited to text,
          graphics, logos, images, workout programs, training methodologies, and
          software, is the property of Hyrax Fitness and is protected by applicable
          intellectual property laws.
        </p>
        <p>
          You may not reproduce, distribute, modify, or create derivative works from
          any content without our prior written consent. Personalized content generated
          for you (workout routines, nutrition plans, coaching responses) is licensed
          for your personal use only.
        </p>
      </section>

      <section className="legal-section" id="terms-12">
        <h2 className="legal-subheading">12. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, Hyrax Fitness, its officers,
          directors, employees, and agents shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from your use
          of our services.
        </p>
        <p>
          This includes, without limitation, damages for personal injury, allergic
          reactions, adverse health effects, loss of data, or loss of profits, whether
          based on warranty, contract, tort, or any other legal theory. Hyrax Fitness
          does not guarantee specific fitness or nutritional results from use of our
          programs.
        </p>
      </section>

      <section className="legal-section" id="terms-13">
        <h2 className="legal-subheading">13. Disclaimer of Warranties</h2>
        <p>
          Our services are provided "as is" and "as available" without any warranties
          of any kind, either express or implied, including but not limited to implied
          warranties of merchantability, fitness for a particular purpose, or
          non-infringement.
        </p>
        <p>
          We do not warrant that the services will be uninterrupted, error-free, or
          secure. We make no representations regarding the accuracy, reliability, or
          completeness of any fitness advice, nutrition recommendations, or content
          provided through our platform, including content generated by automated systems.
        </p>
      </section>

      <section className="legal-section" id="terms-14">
        <h2 className="legal-subheading">14. Termination</h2>
        <p>
          We may terminate or suspend your account and access to our services at our
          sole discretion, without prior notice, for conduct that we determine violates
          these Terms of Use or is harmful to other users or our business interests.
        </p>
        <p>
          You may terminate your account at any time by contacting us. Upon
          termination, your right to use the services will cease immediately. If you
          have an active paid subscription, cancellation terms in Section 5 apply.
        </p>
      </section>

      <section className="legal-section" id="terms-15">
        <h2 className="legal-subheading">15. Governing Law</h2>
        <p>
          These Terms of Use shall be governed by and construed in accordance with the
          laws of the jurisdiction in which Hyrax Fitness operates, without regard to
          its conflict of law principles.
        </p>
        <p>
          Any disputes arising under these terms shall be resolved through binding
          arbitration in accordance with applicable arbitration rules, unless otherwise
          required by law.
        </p>
      </section>

      <section className="legal-section" id="terms-16">
        <h2 className="legal-subheading">16. Changes to These Terms</h2>
        <p>
          We reserve the right to update or modify these Terms of Use at any time. We
          will notify users of material changes by posting the updated terms on this
          page and updating the "Last updated" date. Your continued use of the services
          after changes are posted constitutes acceptance of the revised terms.
        </p>
      </section>

      <section className="legal-section" id="terms-17">
        <h2 className="legal-subheading">17. Contact Information</h2>
        <p>
          If you have any questions about these Terms of Use, please contact us at:
        </p>
        <p>
          <strong>Email:</strong>{' '}
          <a href="mailto:support@hyraxfitness.com">support@hyraxfitness.com</a>
        </p>
        <p>
          <strong>Website:</strong>{' '}
          <Link to="/">hyraxfitness.com</Link>
        </p>
      </section>
    </div>
  );
}
